// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgQIRKKJajMl0cdwGC9R6ltxW_wd69-lY',
    appId: '1:67107507129:web:218a600a1d7b9dbfd60468',
    messagingSenderId: '67107507129',
    projectId: 'chateo-901d0',
    authDomain: 'chateo-901d0.firebaseapp.com',
    storageBucket: 'chateo-901d0.firebasestorage.app',
    measurementId: 'G-3BWQ100KNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_GR6DrqmsCkYUcCEooEPcFyv78kbIOY',
    appId: '1:67107507129:android:1f1470ef44cafeaad60468',
    messagingSenderId: '67107507129',
    projectId: 'chateo-901d0',
    storageBucket: 'chateo-901d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMHXoysoOKyuQmq9REM9EBwRIAfCnv18',
    appId: '1:67107507129:ios:bbdef18b79e88291d60468',
    messagingSenderId: '67107507129',
    projectId: 'chateo-901d0',
    storageBucket: 'chateo-901d0.firebasestorage.app',
    iosBundleId: 'com.example.chateo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByMHXoysoOKyuQmq9REM9EBwRIAfCnv18',
    appId: '1:67107507129:ios:bbdef18b79e88291d60468',
    messagingSenderId: '67107507129',
    projectId: 'chateo-901d0',
    storageBucket: 'chateo-901d0.firebasestorage.app',
    iosBundleId: 'com.example.chateo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgQIRKKJajMl0cdwGC9R6ltxW_wd69-lY',
    appId: '1:67107507129:web:2e4fecbe4244353fd60468',
    messagingSenderId: '67107507129',
    projectId: 'chateo-901d0',
    authDomain: 'chateo-901d0.firebaseapp.com',
    storageBucket: 'chateo-901d0.firebasestorage.app',
    measurementId: 'G-FQR29KLC8D',
  );
}
